function generateMarkdown(data) {
  const lines = [];

  lines.push(`# ${data.url} — Design System Snapshot`);
  lines.push(`Generated by Grid Lens · ${data.date}`);
  lines.push('');

  // ——— Typography Scale ———
  lines.push('## Typography Scale');
  lines.push('');
  if (data.fontSizes && data.fontSizes.length > 0) {
    lines.push(`Sizes: ${data.fontSizes.join(' · ')}px`);
    if (data.scaleRatio) {
      const ratioName = getScaleRatioName(data.scaleRatio);
      lines.push(`Scale ratio: ~${data.scaleRatio} (${ratioName})`);
    }
    lines.push('');
  }
  lines.push('| Element | Font | Size | Weight | Line Height |');
  lines.push('|---------|------|------|--------|-------------|');
  for (const t of data.typography) {
    const lh = t.lineHeight === 'normal' ? 'normal' : t.lineHeight;
    lines.push(`| ${t.tag} | ${t.font} | ${t.size} | ${t.weight} | ${lh} |`);
  }
  lines.push('');

  // ——— Font Families ———
  lines.push('## Font Families');
  lines.push('');
  for (const f of data.fontFamilies) {
    lines.push(`- **${f.name}** — ${f.weights.join(', ')}`);
  }
  lines.push('');

  // ——— Color System ———
  lines.push('## Color System');
  lines.push('');

  // CSS Variables grouped by type
  if (data.cssVars && data.cssVars.length > 0) {
    const colorVars = data.cssVars.filter(v =>
      /color|bg|foreground|background|accent|brand|primary|secondary|error|success|warning/i.test(v.name) ||
      /^(#|rgb|hsl|oklch)/.test(v.value)
    );
    const spacingVars = data.cssVars.filter(v =>
      /space|gap|gutter|padding|margin|radius|border/i.test(v.name) &&
      !colorVars.includes(v)
    );
    const otherVars = data.cssVars.filter(v =>
      !colorVars.includes(v) && !spacingVars.includes(v)
    );

    lines.push('### CSS Variables');
    lines.push('');
    if (colorVars.length > 0) {
      lines.push('**Colors:**');
      lines.push('```css');
      for (const v of colorVars) lines.push(`${v.name}: ${v.value};`);
      lines.push('```');
      lines.push('');
    }
    if (spacingVars.length > 0) {
      lines.push('**Spacing & Layout:**');
      lines.push('```css');
      for (const v of spacingVars) lines.push(`${v.name}: ${v.value};`);
      lines.push('```');
      lines.push('');
    }
    if (otherVars.length > 0) {
      lines.push('**Other:**');
      lines.push('```css');
      for (const v of otherVars) lines.push(`${v.name}: ${v.value};`);
      lines.push('```');
      lines.push('');
    }
  }

  lines.push('### Extracted Palette');
  lines.push('');

  const textColors = data.colors.filter(c => c.usage.includes('text'));
  const bgColors = data.colors.filter(c => c.usage.includes('background'));

  if (textColors.length > 0) {
    lines.push(`**Text:** ${textColors.slice(0, 8).map(c => c.hex).join(', ')}`);
  }
  if (bgColors.length > 0) {
    lines.push(`**Background:** ${bgColors.slice(0, 8).map(c => c.hex).join(', ')}`);
  }

  // Find accent colors (not gray, not black, not white)
  const accentColors = data.colors.filter(c => {
    const r = parseInt(c.hex.slice(1, 3), 16);
    const g = parseInt(c.hex.slice(3, 5), 16);
    const b = parseInt(c.hex.slice(5, 7), 16);
    const max = Math.max(r, g, b), min = Math.min(r, g, b);
    return (max - min) > 30; // has saturation
  });
  if (accentColors.length > 0) {
    lines.push(`**Accent:** ${accentColors.slice(0, 4).map(c => c.hex).join(', ')}`);
  }
  lines.push('');

  // ——— Spacing Scale ———
  if (data.spacingScale && data.spacingScale.length > 0) {
    lines.push('## Spacing Scale');
    lines.push('');
    lines.push(`${data.spacingScale.join(' · ')}px`);
    // Detect if it follows a pattern
    const base = detectSpacingBase(data.spacingScale);
    if (base) {
      lines.push(`Base unit: ${base}px`);
    }
    lines.push('');
  }

  // ——— Layout ———
  if (data.maxWidth) {
    lines.push('## Layout');
    lines.push('');
    lines.push(`Max width: ${data.maxWidth}`);
    lines.push('');
  }

  // ——— Border Radius ———
  if (data.radii && data.radii.length > 0) {
    lines.push('## Border Radius');
    lines.push('');
    const sorted = data.radii
      .map(r => r.value)
      .filter((v, i, a) => a.indexOf(v) === i)
      .sort((a, b) => parseInt(a) - parseInt(b));
    lines.push(sorted.join(' · '));
    lines.push('');
  }

  // ——— Shadows / Elevation ———
  if (data.shadows && data.shadows.length > 0) {
    lines.push('## Shadows');
    lines.push('');
    lines.push('```css');
    data.shadows.forEach((s, i) => {
      const label = i === 0 ? 'sm' : i === 1 ? 'md' : i === 2 ? 'lg' : `${i + 1}`;
      lines.push(`/* ${label} (used ${s.count}x) */`);
      lines.push(`box-shadow: ${s.value};`);
    });
    lines.push('```');
    lines.push('');
  }

  if (data.capped) {
    lines.push('');
    lines.push('> Note: Extraction was capped at 1000 elements. Some tokens may be missing.');
  }

  return lines.join('\n');
}

function getScaleRatioName(ratio) {
  if (ratio >= 1.05 && ratio < 1.15) return 'Minor Second';
  if (ratio >= 1.15 && ratio < 1.2) return 'Major Second';
  if (ratio >= 1.2 && ratio < 1.28) return 'Minor Third';
  if (ratio >= 1.28 && ratio < 1.36) return 'Major Third';
  if (ratio >= 1.36 && ratio < 1.42) return 'Perfect Fourth';
  if (ratio >= 1.42 && ratio < 1.55) return 'Augmented Fourth';
  if (ratio >= 1.55 && ratio < 1.7) return 'Perfect Fifth';
  if (ratio >= 1.7 && ratio < 1.9) return 'Golden Ratio';
  return 'Custom';
}

function detectSpacingBase(scale) {
  // Check if most values are multiples of 4 or 8
  const div4 = scale.filter(v => v % 4 === 0).length;
  const div8 = scale.filter(v => v % 8 === 0).length;
  if (div8 / scale.length > 0.6) return 8;
  if (div4 / scale.length > 0.6) return 4;
  return null;
}

function isLightColor(hex) {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return (r * 299 + g * 587 + b * 114) / 1000 > 186;
}

function getColorName(hex) {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);

  if (r === 0 && g === 0 && b === 0) return 'Black';
  if (r === 255 && g === 255 && b === 255) return 'White';

  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const lightness = (max + min) / 2;

  if (max - min < 20) {
    return lightness > 186 ? 'Light Gray' : lightness > 100 ? 'Gray' : 'Dark Gray';
  }

  if (r > g && r > b) return g > 180 ? 'Yellow' : 'Red';
  if (g > r && g > b) return 'Green';
  if (b > r && b > g) return r > 180 ? 'Purple' : 'Blue';

  return `#${hex.slice(1, 4)}`;
}
